# GitHub Sponsors
github: smartpeopleconnected

# Ko-fi
ko_fi: smartpeopleconnected

# Andere Plattformen (falls du sie nutzt)
# patreon: smartpeopleconnected
# buy_me_a_coffee: smartpeopleconnected

# PayPal direkt (ersetze mit deinem PayPal.me Link)
custom: ["https://paypal.me/sbaessler"]
